[env:esp8266_diagnostics]
platform = espressif8266
board = nodemcuv2
framework = arduino
board_build.f_cpu = 160000000L
monitor_speed = 115200
lib_deps =
    https://github.com/me-no-dev/ESPAsyncWebServer.git
    me-no-dev/ESPAsyncTCP @ ^1.2.2
    bblanchon/ArduinoJson @ ^6.21.3
